# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SYNAPSE_USERNAME: ${{ secrets.SYNAPSE_USERNAME }}
      SYNAPSE_PASSWORD: ${{ secrets.SYNAPSE_PASSWORD }}
      SYNAPSE_PAT: ${{ secrets.SYNAPSE_PAT }}
      SYNAPSE_USERNAME_PUBLIC: ${{ secrets.SYNAPSE_USERNAME_PUBLIC }}
      SYNAPSE_PASSWORD_PUBLIC: ${{ secrets.SYNAPSE_PASSWORD_PUBLIC }}
      SYNAPSE_PAT_PUBLIC: ${{ secrets.SYNAPSE_PAT_PUBLIC }}
      SYNAPSE_USERNAME_NO_TERMS: ${{ secrets.SYNAPSE_USERNAME_NO_TERMS }}
      SYNAPSE_PASSWORD_NO_TERMS: ${{ secrets.SYNAPSE_PASSWORD_NO_TERMS }}
      SYNAPSE_PAT_NO_TERMS: ${{ secrets.SYNAPSE_PAT_NO_TERMS }}

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs
