on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: test-coverage

jobs:
  test-coverage:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SYNAPSE_USERNAME: ${{ secrets.SYNAPSE_USERNAME }}
      SYNAPSE_PASSWORD: ${{ secrets.SYNAPSE_PASSWORD }}
      SYNAPSE_PAT: ${{ secrets.SYNAPSE_PAT }}
      SYNAPSE_USERNAME_PUBLIC: ${{ secrets.SYNAPSE_USERNAME_PUBLIC }}
      SYNAPSE_PASSWORD_PUBLIC: ${{ secrets.SYNAPSE_PASSWORD_PUBLIC }}
      SYNAPSE_PAT_PUBLIC: ${{ secrets.SYNAPSE_PAT_PUBLIC }}
      SYNAPSE_USERNAME_NO_TERMS: ${{ secrets.SYNAPSE_USERNAME_NO_TERMS }}
      SYNAPSE_PASSWORD_NO_TERMS: ${{ secrets.SYNAPSE_PASSWORD_NO_TERMS }}
      SYNAPSE_PAT_NO_TERMS: ${{ secrets.SYNAPSE_PAT_NO_TERMS }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        id: install-r
      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages(c("remotes", "rcmdcheck", "covr"), repos='http://cran.us.r-project.org')
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("GENIE-BPC/genieBPC")
        shell: Rscript {0}

      - name: Test coverage
        env:
          SYNAPSE_USERNAME: ${{ secrets.SYNAPSE_USERNAME }}
          SYNAPSE_PASSWORD: ${{ secrets.SYNAPSE_PASSWORD }}
          SYNAPSE_PAT: ${{ secrets.SYNAPSE_PAT }}
          SYNAPSE_USERNAME_PUBLIC: ${{ secrets.SYNAPSE_USERNAME_PUBLIC }}
          SYNAPSE_PASSWORD_PUBLIC: ${{ secrets.SYNAPSE_PASSWORD_PUBLIC }}
          SYNAPSE_PAT_PUBLIC: ${{ secrets.SYNAPSE_PAT_PUBLIC }}
          SYNAPSE_USERNAME_NO_TERMS: ${{ secrets.SYNAPSE_USERNAME_NO_TERMS }}
          SYNAPSE_PASSWORD_NO_TERMS: ${{ secrets.SYNAPSE_PASSWORD_NO_TERMS }}
          SYNAPSE_PAT_NO_TERMS: ${{ secrets.SYNAPSE_PAT_NO_TERMS }}

        run: |
          genieBPC::set_synapse_credentials()
          covr::codecov()
        shell: Rscript {0}
