on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        id: install-r

      - name: Install dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages(c("remotes", "rcmdcheck", "covr"), repos='http://cran.us.r-project.org')
          remotes::install_deps(dependencies = TRUE)
          synapser::synLogin(email = ${{ secrets.USERNAME }} , password=${{ secrets.SYNAPSER_PAS }},rememberMe = TRUE)
        shell: Rscript {0}

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: covr
          
      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
